# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Macros.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(942, 396)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.LineName11 = QtWidgets.QLineEdit(Form)
        self.LineName11.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName11.setObjectName("LineName11")
        self.gridLayout.addWidget(self.LineName11, 3, 6, 1, 1)
        self.LineName15 = QtWidgets.QLineEdit(Form)
        self.LineName15.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName15.setObjectName("LineName15")
        self.gridLayout.addWidget(self.LineName15, 7, 6, 1, 1)
        self.LblCommand2 = QtWidgets.QLabel(Form)
        self.LblCommand2.setObjectName("LblCommand2")
        self.gridLayout.addWidget(self.LblCommand2, 2, 2, 1, 1)
        self.LineName7 = QtWidgets.QLineEdit(Form)
        self.LineName7.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName7.setObjectName("LineName7")
        self.gridLayout.addWidget(self.LineName7, 9, 1, 1, 1)
        self.LblMacro20 = QtWidgets.QLabel(Form)
        self.LblMacro20.setObjectName("LblMacro20")
        self.gridLayout.addWidget(self.LblMacro20, 12, 5, 1, 1)
        self.LineName3 = QtWidgets.QLineEdit(Form)
        self.LineName3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName3.setObjectName("LineName3")
        self.gridLayout.addWidget(self.LineName3, 5, 1, 1, 1)
        self.LblMacro15 = QtWidgets.QLabel(Form)
        self.LblMacro15.setObjectName("LblMacro15")
        self.gridLayout.addWidget(self.LblMacro15, 7, 5, 1, 1)
        self.LineName4 = QtWidgets.QLineEdit(Form)
        self.LineName4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName4.setObjectName("LineName4")
        self.gridLayout.addWidget(self.LineName4, 6, 1, 1, 1)
        self.LineName18 = QtWidgets.QLineEdit(Form)
        self.LineName18.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName18.setObjectName("LineName18")
        self.gridLayout.addWidget(self.LineName18, 10, 6, 1, 1)
        self.LineName9 = QtWidgets.QLineEdit(Form)
        self.LineName9.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName9.setObjectName("LineName9")
        self.gridLayout.addWidget(self.LineName9, 11, 1, 1, 1)
        self.LineName8 = QtWidgets.QLineEdit(Form)
        self.LineName8.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName8.setObjectName("LineName8")
        self.gridLayout.addWidget(self.LineName8, 10, 1, 1, 1)
        self.LineName5 = QtWidgets.QLineEdit(Form)
        self.LineName5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName5.setObjectName("LineName5")
        self.gridLayout.addWidget(self.LineName5, 7, 1, 1, 1)
        self.LineName16 = QtWidgets.QLineEdit(Form)
        self.LineName16.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName16.setObjectName("LineName16")
        self.gridLayout.addWidget(self.LineName16, 8, 6, 1, 1)
        self.LineName17 = QtWidgets.QLineEdit(Form)
        self.LineName17.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName17.setObjectName("LineName17")
        self.gridLayout.addWidget(self.LineName17, 9, 6, 1, 1)
        self.LineName12 = QtWidgets.QLineEdit(Form)
        self.LineName12.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName12.setObjectName("LineName12")
        self.gridLayout.addWidget(self.LineName12, 4, 6, 1, 1)
        self.LblMacro17 = QtWidgets.QLabel(Form)
        self.LblMacro17.setObjectName("LblMacro17")
        self.gridLayout.addWidget(self.LblMacro17, 9, 5, 1, 1)
        self.LblMacro16 = QtWidgets.QLabel(Form)
        self.LblMacro16.setObjectName("LblMacro16")
        self.gridLayout.addWidget(self.LblMacro16, 8, 5, 1, 1)
        self.LineName6 = QtWidgets.QLineEdit(Form)
        self.LineName6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName6.setObjectName("LineName6")
        self.gridLayout.addWidget(self.LineName6, 8, 1, 1, 1)
        self.LineName20 = QtWidgets.QLineEdit(Form)
        self.LineName20.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName20.setObjectName("LineName20")
        self.gridLayout.addWidget(self.LineName20, 12, 6, 1, 1)
        self.LineName10 = QtWidgets.QLineEdit(Form)
        self.LineName10.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName10.setObjectName("LineName10")
        self.gridLayout.addWidget(self.LineName10, 12, 1, 1, 1)
        self.LblMacro19 = QtWidgets.QLabel(Form)
        self.LblMacro19.setObjectName("LblMacro19")
        self.gridLayout.addWidget(self.LblMacro19, 11, 5, 1, 1)
        self.LineName19 = QtWidgets.QLineEdit(Form)
        self.LineName19.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName19.setObjectName("LineName19")
        self.gridLayout.addWidget(self.LineName19, 11, 6, 1, 1)
        self.LblMacro18 = QtWidgets.QLabel(Form)
        self.LblMacro18.setObjectName("LblMacro18")
        self.gridLayout.addWidget(self.LblMacro18, 10, 5, 1, 1)
        self.LineName13 = QtWidgets.QLineEdit(Form)
        self.LineName13.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName13.setObjectName("LineName13")
        self.gridLayout.addWidget(self.LineName13, 5, 6, 1, 1)
        self.LineName14 = QtWidgets.QLineEdit(Form)
        self.LineName14.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName14.setObjectName("LineName14")
        self.gridLayout.addWidget(self.LineName14, 6, 6, 1, 1)
        self.LblMacro13 = QtWidgets.QLabel(Form)
        self.LblMacro13.setObjectName("LblMacro13")
        self.gridLayout.addWidget(self.LblMacro13, 5, 5, 1, 1)
        self.LblMacro3 = QtWidgets.QLabel(Form)
        self.LblMacro3.setObjectName("LblMacro3")
        self.gridLayout.addWidget(self.LblMacro3, 5, 0, 1, 1)
        self.LblMacro2 = QtWidgets.QLabel(Form)
        self.LblMacro2.setObjectName("LblMacro2")
        self.gridLayout.addWidget(self.LblMacro2, 4, 0, 1, 1)
        self.LblMacro5 = QtWidgets.QLabel(Form)
        self.LblMacro5.setObjectName("LblMacro5")
        self.gridLayout.addWidget(self.LblMacro5, 7, 0, 1, 1)
        self.LblMacro14 = QtWidgets.QLabel(Form)
        self.LblMacro14.setObjectName("LblMacro14")
        self.gridLayout.addWidget(self.LblMacro14, 6, 5, 1, 1)
        self.LblNameSet = QtWidgets.QLabel(Form)
        self.LblNameSet.setObjectName("LblNameSet")
        self.gridLayout.addWidget(self.LblNameSet, 0, 1, 1, 1)
        self.LblMacro6 = QtWidgets.QLabel(Form)
        self.LblMacro6.setObjectName("LblMacro6")
        self.gridLayout.addWidget(self.LblMacro6, 8, 0, 1, 1)
        self.LineCommand2 = QtWidgets.QLineEdit(Form)
        self.LineCommand2.setObjectName("LineCommand2")
        self.gridLayout.addWidget(self.LineCommand2, 4, 2, 1, 3)
        self.LblMacro9 = QtWidgets.QLabel(Form)
        self.LblMacro9.setObjectName("LblMacro9")
        self.gridLayout.addWidget(self.LblMacro9, 11, 0, 1, 1)
        self.LineCommand5 = QtWidgets.QLineEdit(Form)
        self.LineCommand5.setObjectName("LineCommand5")
        self.gridLayout.addWidget(self.LineCommand5, 7, 2, 1, 3)
        self.LblBtnName1 = QtWidgets.QLabel(Form)
        self.LblBtnName1.setObjectName("LblBtnName1")
        self.gridLayout.addWidget(self.LblBtnName1, 2, 1, 1, 1)
        self.LblMacro7 = QtWidgets.QLabel(Form)
        self.LblMacro7.setObjectName("LblMacro7")
        self.gridLayout.addWidget(self.LblMacro7, 9, 0, 1, 1)
        self.LineCommand8 = QtWidgets.QLineEdit(Form)
        self.LineCommand8.setObjectName("LineCommand8")
        self.gridLayout.addWidget(self.LineCommand8, 10, 2, 1, 3)
        self.LineName1 = QtWidgets.QLineEdit(Form)
        self.LineName1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName1.setObjectName("LineName1")
        self.gridLayout.addWidget(self.LineName1, 3, 1, 1, 1)
        self.LineCommand1 = QtWidgets.QLineEdit(Form)
        self.LineCommand1.setObjectName("LineCommand1")
        self.gridLayout.addWidget(self.LineCommand1, 3, 2, 1, 3)
        self.LblMacro11 = QtWidgets.QLabel(Form)
        self.LblMacro11.setObjectName("LblMacro11")
        self.gridLayout.addWidget(self.LblMacro11, 3, 5, 1, 1)
        self.LblMacro4 = QtWidgets.QLabel(Form)
        self.LblMacro4.setObjectName("LblMacro4")
        self.gridLayout.addWidget(self.LblMacro4, 6, 0, 1, 1)
        self.LineCommand7 = QtWidgets.QLineEdit(Form)
        self.LineCommand7.setObjectName("LineCommand7")
        self.gridLayout.addWidget(self.LineCommand7, 9, 2, 1, 3)
        self.LineNameSet = QtWidgets.QLineEdit(Form)
        self.LineNameSet.setObjectName("LineNameSet")
        self.gridLayout.addWidget(self.LineNameSet, 0, 2, 1, 2)
        self.LblMacro12 = QtWidgets.QLabel(Form)
        self.LblMacro12.setObjectName("LblMacro12")
        self.gridLayout.addWidget(self.LblMacro12, 4, 5, 1, 1)
        self.LineCommand6 = QtWidgets.QLineEdit(Form)
        self.LineCommand6.setObjectName("LineCommand6")
        self.gridLayout.addWidget(self.LineCommand6, 8, 2, 1, 3)
        self.LineCommand4 = QtWidgets.QLineEdit(Form)
        self.LineCommand4.setObjectName("LineCommand4")
        self.gridLayout.addWidget(self.LineCommand4, 6, 2, 1, 3)
        self.LineCommand3 = QtWidgets.QLineEdit(Form)
        self.LineCommand3.setObjectName("LineCommand3")
        self.gridLayout.addWidget(self.LineCommand3, 5, 2, 1, 3)
        self.LblCommmand2 = QtWidgets.QLabel(Form)
        self.LblCommmand2.setObjectName("LblCommmand2")
        self.gridLayout.addWidget(self.LblCommmand2, 2, 7, 1, 1)
        self.LblMacro1 = QtWidgets.QLabel(Form)
        self.LblMacro1.setObjectName("LblMacro1")
        self.gridLayout.addWidget(self.LblMacro1, 3, 0, 1, 1)
        self.LblMacro8 = QtWidgets.QLabel(Form)
        self.LblMacro8.setObjectName("LblMacro8")
        self.gridLayout.addWidget(self.LblMacro8, 10, 0, 1, 1)
        self.LineName2 = QtWidgets.QLineEdit(Form)
        self.LineName2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName2.setObjectName("LineName2")
        self.gridLayout.addWidget(self.LineName2, 4, 1, 1, 1)
        self.LblName2 = QtWidgets.QLabel(Form)
        self.LblName2.setObjectName("LblName2")
        self.gridLayout.addWidget(self.LblName2, 2, 6, 1, 1)
        self.LblMacro10 = QtWidgets.QLabel(Form)
        self.LblMacro10.setObjectName("LblMacro10")
        self.gridLayout.addWidget(self.LblMacro10, 12, 0, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 13, 0, 1, 9)
        self.LineCommand19 = QtWidgets.QLineEdit(Form)
        self.LineCommand19.setObjectName("LineCommand19")
        self.gridLayout.addWidget(self.LineCommand19, 11, 7, 1, 2)
        self.LineCommand10 = QtWidgets.QLineEdit(Form)
        self.LineCommand10.setObjectName("LineCommand10")
        self.gridLayout.addWidget(self.LineCommand10, 12, 2, 1, 3)
        self.LineCommand12 = QtWidgets.QLineEdit(Form)
        self.LineCommand12.setObjectName("LineCommand12")
        self.gridLayout.addWidget(self.LineCommand12, 4, 7, 1, 2)
        self.CBMacros = QtWidgets.QComboBox(Form)
        self.CBMacros.setObjectName("CBMacros")
        self.gridLayout.addWidget(self.CBMacros, 0, 4, 1, 1)
        self.LineCommand20 = QtWidgets.QLineEdit(Form)
        self.LineCommand20.setObjectName("LineCommand20")
        self.gridLayout.addWidget(self.LineCommand20, 12, 7, 1, 2)
        self.LineCommand11 = QtWidgets.QLineEdit(Form)
        self.LineCommand11.setObjectName("LineCommand11")
        self.gridLayout.addWidget(self.LineCommand11, 3, 7, 1, 2)
        self.LblStatus = QtWidgets.QLabel(Form)
        self.LblStatus.setText("")
        self.LblStatus.setObjectName("LblStatus")
        self.gridLayout.addWidget(self.LblStatus, 14, 0, 1, 3)
        self.LineCommand18 = QtWidgets.QLineEdit(Form)
        self.LineCommand18.setObjectName("LineCommand18")
        self.gridLayout.addWidget(self.LineCommand18, 10, 7, 1, 2)
        self.BtnDelete = QtWidgets.QPushButton(Form)
        self.BtnDelete.setObjectName("BtnDelete")
        self.gridLayout.addWidget(self.BtnDelete, 0, 8, 1, 1)
        self.LineCommand9 = QtWidgets.QLineEdit(Form)
        self.LineCommand9.setObjectName("LineCommand9")
        self.gridLayout.addWidget(self.LineCommand9, 11, 2, 1, 3)
        self.LineCommand15 = QtWidgets.QLineEdit(Form)
        self.LineCommand15.setObjectName("LineCommand15")
        self.gridLayout.addWidget(self.LineCommand15, 7, 7, 1, 2)
        self.LineCommand13 = QtWidgets.QLineEdit(Form)
        self.LineCommand13.setObjectName("LineCommand13")
        self.gridLayout.addWidget(self.LineCommand13, 5, 7, 1, 2)
        self.LineCommand17 = QtWidgets.QLineEdit(Form)
        self.LineCommand17.setObjectName("LineCommand17")
        self.gridLayout.addWidget(self.LineCommand17, 9, 7, 1, 2)
        self.LineCommand14 = QtWidgets.QLineEdit(Form)
        self.LineCommand14.setObjectName("LineCommand14")
        self.gridLayout.addWidget(self.LineCommand14, 6, 7, 1, 2)
        self.LineCommand16 = QtWidgets.QLineEdit(Form)
        self.LineCommand16.setObjectName("LineCommand16")
        self.gridLayout.addWidget(self.LineCommand16, 8, 7, 1, 2)
        self.BtnSave = QtWidgets.QPushButton(Form)
        self.BtnSave.setObjectName("BtnSave")
        self.gridLayout.addWidget(self.BtnSave, 0, 7, 1, 1)
        self.BtnAll = QtWidgets.QPushButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Save/icon/floppy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnAll.setIcon(icon)
        self.BtnAll.setObjectName("BtnAll")
        self.gridLayout.addWidget(self.BtnAll, 0, 6, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.LineNameSet, self.LineName1)
        Form.setTabOrder(self.LineName1, self.LineCommand1)
        Form.setTabOrder(self.LineCommand1, self.LineName2)
        Form.setTabOrder(self.LineName2, self.LineCommand2)
        Form.setTabOrder(self.LineCommand2, self.LineName3)
        Form.setTabOrder(self.LineName3, self.LineCommand3)
        Form.setTabOrder(self.LineCommand3, self.LineName4)
        Form.setTabOrder(self.LineName4, self.LineCommand4)
        Form.setTabOrder(self.LineCommand4, self.LineName5)
        Form.setTabOrder(self.LineName5, self.LineCommand5)
        Form.setTabOrder(self.LineCommand5, self.LineName6)
        Form.setTabOrder(self.LineName6, self.LineCommand6)
        Form.setTabOrder(self.LineCommand6, self.LineName7)
        Form.setTabOrder(self.LineName7, self.LineCommand7)
        Form.setTabOrder(self.LineCommand7, self.LineName8)
        Form.setTabOrder(self.LineName8, self.LineCommand8)
        Form.setTabOrder(self.LineCommand8, self.LineName9)
        Form.setTabOrder(self.LineName9, self.LineCommand9)
        Form.setTabOrder(self.LineCommand9, self.LineName10)
        Form.setTabOrder(self.LineName10, self.LineCommand10)
        Form.setTabOrder(self.LineCommand10, self.LineName11)
        Form.setTabOrder(self.LineName11, self.LineCommand11)
        Form.setTabOrder(self.LineCommand11, self.LineName12)
        Form.setTabOrder(self.LineName12, self.LineCommand12)
        Form.setTabOrder(self.LineCommand12, self.LineName13)
        Form.setTabOrder(self.LineName13, self.LineCommand13)
        Form.setTabOrder(self.LineCommand13, self.LineName14)
        Form.setTabOrder(self.LineName14, self.LineCommand14)
        Form.setTabOrder(self.LineCommand14, self.LineName15)
        Form.setTabOrder(self.LineName15, self.LineCommand15)
        Form.setTabOrder(self.LineCommand15, self.LineName16)
        Form.setTabOrder(self.LineName16, self.LineCommand16)
        Form.setTabOrder(self.LineCommand16, self.LineName17)
        Form.setTabOrder(self.LineName17, self.LineCommand17)
        Form.setTabOrder(self.LineCommand17, self.LineName18)
        Form.setTabOrder(self.LineName18, self.LineCommand18)
        Form.setTabOrder(self.LineCommand18, self.LineName19)
        Form.setTabOrder(self.LineName19, self.LineCommand19)
        Form.setTabOrder(self.LineCommand19, self.LineName20)
        Form.setTabOrder(self.LineName20, self.LineCommand20)
        Form.setTabOrder(self.LineCommand20, self.BtnAll)
        Form.setTabOrder(self.BtnAll, self.BtnSave)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MacrosSet"))
        self.LblCommand2.setText(_translate("Form", "Command:"))
        self.LblMacro20.setText(_translate("Form", "Macro20"))
        self.LblMacro15.setText(_translate("Form", "Macro15"))
        self.LblMacro17.setText(_translate("Form", "Macro17"))
        self.LblMacro16.setText(_translate("Form", "Macro16"))
        self.LblMacro19.setText(_translate("Form", "Macro19"))
        self.LblMacro18.setText(_translate("Form", "Macro18"))
        self.LblMacro13.setText(_translate("Form", "Macro13"))
        self.LblMacro3.setText(_translate("Form", "Macro3"))
        self.LblMacro2.setText(_translate("Form", "Macro2"))
        self.LblMacro5.setText(_translate("Form", "Macro5"))
        self.LblMacro14.setText(_translate("Form", "Macro14"))
        self.LblNameSet.setText(_translate("Form", "Name of Macros Set:"))
        self.LblMacro6.setText(_translate("Form", "Macro6"))
        self.LblMacro9.setText(_translate("Form", "Macro9"))
        self.LblBtnName1.setText(_translate("Form", "Name on Button:"))
        self.LblMacro7.setText(_translate("Form", "Macro7"))
        self.LblMacro11.setText(_translate("Form", "Macro11"))
        self.LblMacro4.setText(_translate("Form", "Macro4"))
        self.LblMacro12.setText(_translate("Form", "Macro12"))
        self.LblCommmand2.setText(_translate("Form", "Command:"))
        self.LblMacro1.setText(_translate("Form", "Macro1"))
        self.LblMacro8.setText(_translate("Form", "Macro8"))
        self.LblName2.setText(_translate("Form", "Name on Button:"))
        self.LblMacro10.setText(_translate("Form", "Macro10"))
        self.BtnDelete.setText(_translate("Form", "Delete"))
        self.BtnSave.setText(_translate("Form", "Save only"))
        self.BtnAll.setText(_translate("Form", "Save and Apply"))

import logo_rc
