# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Macros.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1030, 637)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.BtnSend27 = QtWidgets.QPushButton(Form)
        self.BtnSend27.setObjectName("BtnSend27")
        self.gridLayout.addWidget(self.BtnSend27, 14, 12, 1, 1)
        self.BtnIcon10 = QtWidgets.QPushButton(Form)
        self.BtnIcon10.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/ic_collections_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnIcon10.setIcon(icon)
        self.BtnIcon10.setObjectName("BtnIcon10")
        self.gridLayout.addWidget(self.BtnIcon10, 12, 6, 1, 1)
        self.BtnSend23 = QtWidgets.QPushButton(Form)
        self.BtnSend23.setObjectName("BtnSend23")
        self.gridLayout.addWidget(self.BtnSend23, 10, 12, 1, 1)
        self.BtnIcon13 = QtWidgets.QPushButton(Form)
        self.BtnIcon13.setText("")
        self.BtnIcon13.setIcon(icon)
        self.BtnIcon13.setObjectName("BtnIcon13")
        self.gridLayout.addWidget(self.BtnIcon13, 15, 6, 1, 1)
        self.BtnIcon7 = QtWidgets.QPushButton(Form)
        self.BtnIcon7.setText("")
        self.BtnIcon7.setIcon(icon)
        self.BtnIcon7.setObjectName("BtnIcon7")
        self.gridLayout.addWidget(self.BtnIcon7, 9, 6, 1, 1)
        self.BtnIcon9 = QtWidgets.QPushButton(Form)
        self.BtnIcon9.setText("")
        self.BtnIcon9.setIcon(icon)
        self.BtnIcon9.setObjectName("BtnIcon9")
        self.gridLayout.addWidget(self.BtnIcon9, 11, 6, 1, 1)
        self.BtnIcon12 = QtWidgets.QPushButton(Form)
        self.BtnIcon12.setText("")
        self.BtnIcon12.setIcon(icon)
        self.BtnIcon12.setObjectName("BtnIcon12")
        self.gridLayout.addWidget(self.BtnIcon12, 14, 6, 1, 1)
        self.BtnIcon3 = QtWidgets.QPushButton(Form)
        self.BtnIcon3.setText("")
        self.BtnIcon3.setIcon(icon)
        self.BtnIcon3.setObjectName("BtnIcon3")
        self.gridLayout.addWidget(self.BtnIcon3, 5, 6, 1, 1)
        self.BtnSend22 = QtWidgets.QPushButton(Form)
        self.BtnSend22.setObjectName("BtnSend22")
        self.gridLayout.addWidget(self.BtnSend22, 9, 12, 1, 1)
        self.BtnIcon15 = QtWidgets.QPushButton(Form)
        self.BtnIcon15.setText("")
        self.BtnIcon15.setIcon(icon)
        self.BtnIcon15.setObjectName("BtnIcon15")
        self.gridLayout.addWidget(self.BtnIcon15, 17, 6, 1, 1)
        self.BtnIcon2 = QtWidgets.QPushButton(Form)
        self.BtnIcon2.setText("")
        self.BtnIcon2.setIcon(icon)
        self.BtnIcon2.setObjectName("BtnIcon2")
        self.gridLayout.addWidget(self.BtnIcon2, 4, 6, 1, 1)
        self.BtnIcon1 = QtWidgets.QPushButton(Form)
        self.BtnIcon1.setText("")
        self.BtnIcon1.setIcon(icon)
        self.BtnIcon1.setObjectName("BtnIcon1")
        self.gridLayout.addWidget(self.BtnIcon1, 3, 6, 1, 1)
        self.BtnIcon6 = QtWidgets.QPushButton(Form)
        self.BtnIcon6.setText("")
        self.BtnIcon6.setIcon(icon)
        self.BtnIcon6.setObjectName("BtnIcon6")
        self.gridLayout.addWidget(self.BtnIcon6, 8, 6, 1, 1)
        self.BtnIcon11 = QtWidgets.QPushButton(Form)
        self.BtnIcon11.setText("")
        self.BtnIcon11.setIcon(icon)
        self.BtnIcon11.setObjectName("BtnIcon11")
        self.gridLayout.addWidget(self.BtnIcon11, 13, 6, 1, 1)
        self.BtnIcon8 = QtWidgets.QPushButton(Form)
        self.BtnIcon8.setText("")
        self.BtnIcon8.setIcon(icon)
        self.BtnIcon8.setObjectName("BtnIcon8")
        self.gridLayout.addWidget(self.BtnIcon8, 10, 6, 1, 1)
        self.BtnSend28 = QtWidgets.QPushButton(Form)
        self.BtnSend28.setObjectName("BtnSend28")
        self.gridLayout.addWidget(self.BtnSend28, 15, 12, 1, 1)
        self.BtnSend19 = QtWidgets.QPushButton(Form)
        self.BtnSend19.setObjectName("BtnSend19")
        self.gridLayout.addWidget(self.BtnSend19, 6, 12, 1, 1)
        self.BtnIcon5 = QtWidgets.QPushButton(Form)
        self.BtnIcon5.setText("")
        self.BtnIcon5.setIcon(icon)
        self.BtnIcon5.setObjectName("BtnIcon5")
        self.gridLayout.addWidget(self.BtnIcon5, 7, 6, 1, 1)
        self.BtnIcon4 = QtWidgets.QPushButton(Form)
        self.BtnIcon4.setText("")
        self.BtnIcon4.setIcon(icon)
        self.BtnIcon4.setObjectName("BtnIcon4")
        self.gridLayout.addWidget(self.BtnIcon4, 6, 6, 1, 1)
        self.BtnIcon14 = QtWidgets.QPushButton(Form)
        self.BtnIcon14.setText("")
        self.BtnIcon14.setIcon(icon)
        self.BtnIcon14.setObjectName("BtnIcon14")
        self.gridLayout.addWidget(self.BtnIcon14, 16, 6, 1, 1)
        self.BtnSend24 = QtWidgets.QPushButton(Form)
        self.BtnSend24.setObjectName("BtnSend24")
        self.gridLayout.addWidget(self.BtnSend24, 11, 12, 1, 1)
        self.LineName4 = QtWidgets.QLineEdit(Form)
        self.LineName4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName4.setObjectName("LineName4")
        self.gridLayout.addWidget(self.LineName4, 6, 1, 1, 1)
        self.LineCommand3 = QtWidgets.QLineEdit(Form)
        self.LineCommand3.setObjectName("LineCommand3")
        self.gridLayout.addWidget(self.LineCommand3, 5, 2, 1, 3)
        self.LineName8 = QtWidgets.QLineEdit(Form)
        self.LineName8.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName8.setObjectName("LineName8")
        self.gridLayout.addWidget(self.LineName8, 10, 1, 1, 1)
        self.LblMacro7 = QtWidgets.QLabel(Form)
        self.LblMacro7.setObjectName("LblMacro7")
        self.gridLayout.addWidget(self.LblMacro7, 9, 0, 1, 1)
        self.LblMacro9 = QtWidgets.QLabel(Form)
        self.LblMacro9.setObjectName("LblMacro9")
        self.gridLayout.addWidget(self.LblMacro9, 11, 0, 1, 1)
        self.LineName9 = QtWidgets.QLineEdit(Form)
        self.LineName9.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName9.setObjectName("LineName9")
        self.gridLayout.addWidget(self.LineName9, 11, 1, 1, 1)
        self.LineCommand7 = QtWidgets.QLineEdit(Form)
        self.LineCommand7.setObjectName("LineCommand7")
        self.gridLayout.addWidget(self.LineCommand7, 9, 2, 1, 3)
        self.LblNameSet = QtWidgets.QLabel(Form)
        self.LblNameSet.setObjectName("LblNameSet")
        self.gridLayout.addWidget(self.LblNameSet, 0, 1, 1, 1)
        self.LblMacro8 = QtWidgets.QLabel(Form)
        self.LblMacro8.setObjectName("LblMacro8")
        self.gridLayout.addWidget(self.LblMacro8, 10, 0, 1, 1)
        self.LineCommand2 = QtWidgets.QLineEdit(Form)
        self.LineCommand2.setObjectName("LineCommand2")
        self.gridLayout.addWidget(self.LineCommand2, 4, 2, 1, 3)
        self.LblMacro2 = QtWidgets.QLabel(Form)
        self.LblMacro2.setObjectName("LblMacro2")
        self.gridLayout.addWidget(self.LblMacro2, 4, 0, 1, 1)
        self.LineName10 = QtWidgets.QLineEdit(Form)
        self.LineName10.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName10.setObjectName("LineName10")
        self.gridLayout.addWidget(self.LineName10, 12, 1, 1, 1)
        self.LineCommand5 = QtWidgets.QLineEdit(Form)
        self.LineCommand5.setObjectName("LineCommand5")
        self.gridLayout.addWidget(self.LineCommand5, 7, 2, 1, 3)
        self.LineCommand1 = QtWidgets.QLineEdit(Form)
        self.LineCommand1.setObjectName("LineCommand1")
        self.gridLayout.addWidget(self.LineCommand1, 3, 2, 1, 3)
        self.LblMacro3 = QtWidgets.QLabel(Form)
        self.LblMacro3.setObjectName("LblMacro3")
        self.gridLayout.addWidget(self.LblMacro3, 5, 0, 1, 1)
        self.LblMacro5 = QtWidgets.QLabel(Form)
        self.LblMacro5.setObjectName("LblMacro5")
        self.gridLayout.addWidget(self.LblMacro5, 7, 0, 1, 1)
        self.LineName5 = QtWidgets.QLineEdit(Form)
        self.LineName5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName5.setObjectName("LineName5")
        self.gridLayout.addWidget(self.LineName5, 7, 1, 1, 1)
        self.LineCommand8 = QtWidgets.QLineEdit(Form)
        self.LineCommand8.setObjectName("LineCommand8")
        self.gridLayout.addWidget(self.LineCommand8, 10, 2, 1, 3)
        self.LblCommand2 = QtWidgets.QLabel(Form)
        self.LblCommand2.setObjectName("LblCommand2")
        self.gridLayout.addWidget(self.LblCommand2, 2, 2, 1, 1)
        self.LineName7 = QtWidgets.QLineEdit(Form)
        self.LineName7.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName7.setObjectName("LineName7")
        self.gridLayout.addWidget(self.LineName7, 9, 1, 1, 1)
        self.LineName3 = QtWidgets.QLineEdit(Form)
        self.LineName3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName3.setObjectName("LineName3")
        self.gridLayout.addWidget(self.LineName3, 5, 1, 1, 1)
        self.LineName6 = QtWidgets.QLineEdit(Form)
        self.LineName6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName6.setObjectName("LineName6")
        self.gridLayout.addWidget(self.LineName6, 8, 1, 1, 1)
        self.LblMacro6 = QtWidgets.QLabel(Form)
        self.LblMacro6.setObjectName("LblMacro6")
        self.gridLayout.addWidget(self.LblMacro6, 8, 0, 1, 1)
        self.LineName1 = QtWidgets.QLineEdit(Form)
        self.LineName1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName1.setObjectName("LineName1")
        self.gridLayout.addWidget(self.LineName1, 3, 1, 1, 1)
        self.LblBtnName1 = QtWidgets.QLabel(Form)
        self.LblBtnName1.setObjectName("LblBtnName1")
        self.gridLayout.addWidget(self.LblBtnName1, 2, 1, 1, 1)
        self.LineCommand6 = QtWidgets.QLineEdit(Form)
        self.LineCommand6.setObjectName("LineCommand6")
        self.gridLayout.addWidget(self.LineCommand6, 8, 2, 1, 3)
        self.BtnSend13 = QtWidgets.QPushButton(Form)
        self.BtnSend13.setObjectName("BtnSend13")
        self.gridLayout.addWidget(self.BtnSend13, 15, 5, 1, 1)
        self.BtnSend12 = QtWidgets.QPushButton(Form)
        self.BtnSend12.setObjectName("BtnSend12")
        self.gridLayout.addWidget(self.BtnSend12, 14, 5, 1, 1)
        self.BtnSend8 = QtWidgets.QPushButton(Form)
        self.BtnSend8.setObjectName("BtnSend8")
        self.gridLayout.addWidget(self.BtnSend8, 10, 5, 1, 1)
        self.LblMacro10 = QtWidgets.QLabel(Form)
        self.LblMacro10.setObjectName("LblMacro10")
        self.gridLayout.addWidget(self.LblMacro10, 12, 0, 1, 1)
        self.LblMacro21 = QtWidgets.QLabel(Form)
        self.LblMacro21.setObjectName("LblMacro21")
        self.gridLayout.addWidget(self.LblMacro21, 8, 8, 1, 1)
        self.CBMacros = QtWidgets.QComboBox(Form)
        self.CBMacros.setObjectName("CBMacros")
        self.gridLayout.addWidget(self.CBMacros, 0, 4, 1, 1)
        self.LblCommmand2 = QtWidgets.QLabel(Form)
        self.LblCommmand2.setObjectName("LblCommmand2")
        self.gridLayout.addWidget(self.LblCommmand2, 2, 10, 1, 1)
        self.LblMacro1 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LblMacro1.sizePolicy().hasHeightForWidth())
        self.LblMacro1.setSizePolicy(sizePolicy)
        self.LblMacro1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.LblMacro1.setObjectName("LblMacro1")
        self.gridLayout.addWidget(self.LblMacro1, 3, 0, 1, 1)
        self.BtnSend14 = QtWidgets.QPushButton(Form)
        self.BtnSend14.setObjectName("BtnSend14")
        self.gridLayout.addWidget(self.BtnSend14, 16, 5, 1, 1)
        self.BtnSend9 = QtWidgets.QPushButton(Form)
        self.BtnSend9.setObjectName("BtnSend9")
        self.gridLayout.addWidget(self.BtnSend9, 11, 5, 1, 1)
        self.LineCommand10 = QtWidgets.QLineEdit(Form)
        self.LineCommand10.setObjectName("LineCommand10")
        self.gridLayout.addWidget(self.LineCommand10, 12, 2, 1, 3)
        self.LineCommand4 = QtWidgets.QLineEdit(Form)
        self.LineCommand4.setObjectName("LineCommand4")
        self.gridLayout.addWidget(self.LineCommand4, 6, 2, 1, 3)
        self.LineNameSet = QtWidgets.QLineEdit(Form)
        self.LineNameSet.setObjectName("LineNameSet")
        self.gridLayout.addWidget(self.LineNameSet, 0, 2, 1, 2)
        self.LblMacro25 = QtWidgets.QLabel(Form)
        self.LblMacro25.setObjectName("LblMacro25")
        self.gridLayout.addWidget(self.LblMacro25, 12, 8, 1, 1)
        self.LblMacro24 = QtWidgets.QLabel(Form)
        self.LblMacro24.setObjectName("LblMacro24")
        self.gridLayout.addWidget(self.LblMacro24, 11, 8, 1, 1)
        self.LineName2 = QtWidgets.QLineEdit(Form)
        self.LineName2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName2.setObjectName("LineName2")
        self.gridLayout.addWidget(self.LineName2, 4, 1, 1, 1)
        self.BtnSend2 = QtWidgets.QPushButton(Form)
        self.BtnSend2.setObjectName("BtnSend2")
        self.gridLayout.addWidget(self.BtnSend2, 4, 5, 1, 1)
        self.BtnSend11 = QtWidgets.QPushButton(Form)
        self.BtnSend11.setObjectName("BtnSend11")
        self.gridLayout.addWidget(self.BtnSend11, 13, 5, 1, 1)
        self.LblName2 = QtWidgets.QLabel(Form)
        self.LblName2.setObjectName("LblName2")
        self.gridLayout.addWidget(self.LblName2, 2, 9, 1, 1)
        self.LblMacro27 = QtWidgets.QLabel(Form)
        self.LblMacro27.setObjectName("LblMacro27")
        self.gridLayout.addWidget(self.LblMacro27, 14, 8, 1, 1)
        self.BtnSend4 = QtWidgets.QPushButton(Form)
        self.BtnSend4.setObjectName("BtnSend4")
        self.gridLayout.addWidget(self.BtnSend4, 6, 5, 1, 1)
        self.BtnSend6 = QtWidgets.QPushButton(Form)
        self.BtnSend6.setObjectName("BtnSend6")
        self.gridLayout.addWidget(self.BtnSend6, 8, 5, 1, 1)
        self.LblMacro4 = QtWidgets.QLabel(Form)
        self.LblMacro4.setObjectName("LblMacro4")
        self.gridLayout.addWidget(self.LblMacro4, 6, 0, 1, 1)
        self.BtnSend7 = QtWidgets.QPushButton(Form)
        self.BtnSend7.setObjectName("BtnSend7")
        self.gridLayout.addWidget(self.BtnSend7, 9, 5, 1, 1)
        self.LblMacro26 = QtWidgets.QLabel(Form)
        self.LblMacro26.setObjectName("LblMacro26")
        self.gridLayout.addWidget(self.LblMacro26, 13, 8, 1, 1)
        self.LblMacro22 = QtWidgets.QLabel(Form)
        self.LblMacro22.setObjectName("LblMacro22")
        self.gridLayout.addWidget(self.LblMacro22, 9, 8, 1, 1)
        self.BtnDelete = QtWidgets.QPushButton(Form)
        self.BtnDelete.setObjectName("BtnDelete")
        self.gridLayout.addWidget(self.BtnDelete, 0, 11, 1, 1)
        self.LineCommand21 = QtWidgets.QLineEdit(Form)
        self.LineCommand21.setObjectName("LineCommand21")
        self.gridLayout.addWidget(self.LineCommand21, 8, 10, 1, 2)
        self.LblStatus = QtWidgets.QLabel(Form)
        self.LblStatus.setText("")
        self.LblStatus.setObjectName("LblStatus")
        self.gridLayout.addWidget(self.LblStatus, 19, 0, 1, 3)
        self.LineCommand9 = QtWidgets.QLineEdit(Form)
        self.LineCommand9.setObjectName("LineCommand9")
        self.gridLayout.addWidget(self.LineCommand9, 11, 2, 1, 3)
        self.LineCommand14 = QtWidgets.QLineEdit(Form)
        self.LineCommand14.setObjectName("LineCommand14")
        self.gridLayout.addWidget(self.LineCommand14, 16, 2, 1, 3)
        self.LblMacro14 = QtWidgets.QLabel(Form)
        self.LblMacro14.setObjectName("LblMacro14")
        self.gridLayout.addWidget(self.LblMacro14, 16, 0, 1, 1)
        self.LineCommand30 = QtWidgets.QLineEdit(Form)
        self.LineCommand30.setObjectName("LineCommand30")
        self.gridLayout.addWidget(self.LineCommand30, 17, 10, 1, 2)
        self.LblLabel30 = QtWidgets.QLabel(Form)
        self.LblLabel30.setObjectName("LblLabel30")
        self.gridLayout.addWidget(self.LblLabel30, 17, 8, 1, 1)
        self.LineCommand12 = QtWidgets.QLineEdit(Form)
        self.LineCommand12.setObjectName("LineCommand12")
        self.gridLayout.addWidget(self.LineCommand12, 14, 2, 1, 3)
        self.LineName25 = QtWidgets.QLineEdit(Form)
        self.LineName25.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName25.setObjectName("LineName25")
        self.gridLayout.addWidget(self.LineName25, 12, 9, 1, 1)
        self.BtnSend10 = QtWidgets.QPushButton(Form)
        self.BtnSend10.setObjectName("BtnSend10")
        self.gridLayout.addWidget(self.BtnSend10, 12, 5, 1, 1)
        self.LblMacro28 = QtWidgets.QLabel(Form)
        self.LblMacro28.setObjectName("LblMacro28")
        self.gridLayout.addWidget(self.LblMacro28, 15, 8, 1, 1)
        self.LineName28 = QtWidgets.QLineEdit(Form)
        self.LineName28.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName28.setObjectName("LineName28")
        self.gridLayout.addWidget(self.LineName28, 15, 9, 1, 1)
        self.BtnSend15 = QtWidgets.QPushButton(Form)
        self.BtnSend15.setObjectName("BtnSend15")
        self.gridLayout.addWidget(self.BtnSend15, 17, 5, 1, 1)
        self.LblMacro15 = QtWidgets.QLabel(Form)
        self.LblMacro15.setObjectName("LblMacro15")
        self.gridLayout.addWidget(self.LblMacro15, 17, 0, 1, 1)
        self.LineName26 = QtWidgets.QLineEdit(Form)
        self.LineName26.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName26.setObjectName("LineName26")
        self.gridLayout.addWidget(self.LineName26, 13, 9, 1, 1)
        self.BtnSend3 = QtWidgets.QPushButton(Form)
        self.BtnSend3.setObjectName("BtnSend3")
        self.gridLayout.addWidget(self.BtnSend3, 5, 5, 1, 1)
        self.LineName12 = QtWidgets.QLineEdit(Form)
        self.LineName12.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName12.setObjectName("LineName12")
        self.gridLayout.addWidget(self.LineName12, 14, 1, 1, 1)
        self.LineName24 = QtWidgets.QLineEdit(Form)
        self.LineName24.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName24.setObjectName("LineName24")
        self.gridLayout.addWidget(self.LineName24, 11, 9, 1, 1)
        self.LineCommand15 = QtWidgets.QLineEdit(Form)
        self.LineCommand15.setObjectName("LineCommand15")
        self.gridLayout.addWidget(self.LineCommand15, 17, 2, 1, 3)
        self.LineName27 = QtWidgets.QLineEdit(Form)
        self.LineName27.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName27.setObjectName("LineName27")
        self.gridLayout.addWidget(self.LineName27, 14, 9, 1, 1)
        self.LineCommand13 = QtWidgets.QLineEdit(Form)
        self.LineCommand13.setObjectName("LineCommand13")
        self.gridLayout.addWidget(self.LineCommand13, 15, 2, 1, 3)
        self.LineName13 = QtWidgets.QLineEdit(Form)
        self.LineName13.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName13.setObjectName("LineName13")
        self.gridLayout.addWidget(self.LineName13, 15, 1, 1, 1)
        self.LblMacro20 = QtWidgets.QLabel(Form)
        self.LblMacro20.setObjectName("LblMacro20")
        self.gridLayout.addWidget(self.LblMacro20, 7, 8, 1, 1)
        self.LblMacro23 = QtWidgets.QLabel(Form)
        self.LblMacro23.setObjectName("LblMacro23")
        self.gridLayout.addWidget(self.LblMacro23, 10, 8, 1, 1)
        self.LblMacro12 = QtWidgets.QLabel(Form)
        self.LblMacro12.setObjectName("LblMacro12")
        self.gridLayout.addWidget(self.LblMacro12, 14, 0, 1, 1)
        self.LblMacro11 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LblMacro11.sizePolicy().hasHeightForWidth())
        self.LblMacro11.setSizePolicy(sizePolicy)
        self.LblMacro11.setMaximumSize(QtCore.QSize(60, 16777215))
        self.LblMacro11.setObjectName("LblMacro11")
        self.gridLayout.addWidget(self.LblMacro11, 13, 0, 1, 1)
        self.LineName15 = QtWidgets.QLineEdit(Form)
        self.LineName15.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName15.setObjectName("LineName15")
        self.gridLayout.addWidget(self.LineName15, 17, 1, 1, 1)
        self.LineCommand11 = QtWidgets.QLineEdit(Form)
        self.LineCommand11.setObjectName("LineCommand11")
        self.gridLayout.addWidget(self.LineCommand11, 13, 2, 1, 3)
        self.LblMacro16 = QtWidgets.QLabel(Form)
        self.LblMacro16.setObjectName("LblMacro16")
        self.gridLayout.addWidget(self.LblMacro16, 3, 8, 1, 1)
        self.LineName11 = QtWidgets.QLineEdit(Form)
        self.LineName11.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName11.setObjectName("LineName11")
        self.gridLayout.addWidget(self.LineName11, 13, 1, 1, 1)
        self.LblMacro18 = QtWidgets.QLabel(Form)
        self.LblMacro18.setObjectName("LblMacro18")
        self.gridLayout.addWidget(self.LblMacro18, 5, 8, 1, 1)
        self.LineName30 = QtWidgets.QLineEdit(Form)
        self.LineName30.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName30.setObjectName("LineName30")
        self.gridLayout.addWidget(self.LineName30, 17, 9, 1, 1)
        self.LineCommand29 = QtWidgets.QLineEdit(Form)
        self.LineCommand29.setObjectName("LineCommand29")
        self.gridLayout.addWidget(self.LineCommand29, 16, 10, 1, 2)
        self.BtnSend5 = QtWidgets.QPushButton(Form)
        self.BtnSend5.setObjectName("BtnSend5")
        self.gridLayout.addWidget(self.BtnSend5, 7, 5, 1, 1)
        self.LineName29 = QtWidgets.QLineEdit(Form)
        self.LineName29.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName29.setObjectName("LineName29")
        self.gridLayout.addWidget(self.LineName29, 16, 9, 1, 1)
        self.LineCommand24 = QtWidgets.QLineEdit(Form)
        self.LineCommand24.setObjectName("LineCommand24")
        self.gridLayout.addWidget(self.LineCommand24, 11, 10, 1, 2)
        self.LineCommand28 = QtWidgets.QLineEdit(Form)
        self.LineCommand28.setObjectName("LineCommand28")
        self.gridLayout.addWidget(self.LineCommand28, 15, 10, 1, 2)
        self.LblMacro19 = QtWidgets.QLabel(Form)
        self.LblMacro19.setObjectName("LblMacro19")
        self.gridLayout.addWidget(self.LblMacro19, 6, 8, 1, 1)
        self.LineCommand23 = QtWidgets.QLineEdit(Form)
        self.LineCommand23.setObjectName("LineCommand23")
        self.gridLayout.addWidget(self.LineCommand23, 10, 10, 1, 2)
        self.LineName17 = QtWidgets.QLineEdit(Form)
        self.LineName17.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName17.setObjectName("LineName17")
        self.gridLayout.addWidget(self.LineName17, 4, 9, 1, 1)
        self.BtnAll = QtWidgets.QPushButton(Form)
        self.BtnAll.setMaximumSize(QtCore.QSize(150, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Save/icon/floppy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnAll.setIcon(icon1)
        self.BtnAll.setObjectName("BtnAll")
        self.gridLayout.addWidget(self.BtnAll, 0, 9, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 7, 16, 1)
        self.BtnSave = QtWidgets.QPushButton(Form)
        self.BtnSave.setObjectName("BtnSave")
        self.gridLayout.addWidget(self.BtnSave, 0, 10, 1, 1)
        self.LineName14 = QtWidgets.QLineEdit(Form)
        self.LineName14.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName14.setObjectName("LineName14")
        self.gridLayout.addWidget(self.LineName14, 16, 1, 1, 1)
        self.LblMacro13 = QtWidgets.QLabel(Form)
        self.LblMacro13.setObjectName("LblMacro13")
        self.gridLayout.addWidget(self.LblMacro13, 15, 0, 1, 1)
        self.LineCommand19 = QtWidgets.QLineEdit(Form)
        self.LineCommand19.setObjectName("LineCommand19")
        self.gridLayout.addWidget(self.LineCommand19, 6, 10, 1, 2)
        self.LineCommand22 = QtWidgets.QLineEdit(Form)
        self.LineCommand22.setObjectName("LineCommand22")
        self.gridLayout.addWidget(self.LineCommand22, 9, 10, 1, 2)
        self.LineCommand27 = QtWidgets.QLineEdit(Form)
        self.LineCommand27.setObjectName("LineCommand27")
        self.gridLayout.addWidget(self.LineCommand27, 14, 10, 1, 2)
        self.LineName18 = QtWidgets.QLineEdit(Form)
        self.LineName18.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName18.setObjectName("LineName18")
        self.gridLayout.addWidget(self.LineName18, 5, 9, 1, 1)
        self.BtnSend16 = QtWidgets.QPushButton(Form)
        self.BtnSend16.setObjectName("BtnSend16")
        self.gridLayout.addWidget(self.BtnSend16, 3, 12, 1, 1)
        self.LblMacro17 = QtWidgets.QLabel(Form)
        self.LblMacro17.setObjectName("LblMacro17")
        self.gridLayout.addWidget(self.LblMacro17, 4, 8, 1, 1)
        self.LineName22 = QtWidgets.QLineEdit(Form)
        self.LineName22.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName22.setObjectName("LineName22")
        self.gridLayout.addWidget(self.LineName22, 9, 9, 1, 1)
        self.LineCommand17 = QtWidgets.QLineEdit(Form)
        self.LineCommand17.setObjectName("LineCommand17")
        self.gridLayout.addWidget(self.LineCommand17, 4, 10, 1, 2)
        self.LineName16 = QtWidgets.QLineEdit(Form)
        self.LineName16.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName16.setObjectName("LineName16")
        self.gridLayout.addWidget(self.LineName16, 3, 9, 1, 1)
        self.LineName21 = QtWidgets.QLineEdit(Form)
        self.LineName21.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName21.setObjectName("LineName21")
        self.gridLayout.addWidget(self.LineName21, 8, 9, 1, 1)
        self.LineName20 = QtWidgets.QLineEdit(Form)
        self.LineName20.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName20.setObjectName("LineName20")
        self.gridLayout.addWidget(self.LineName20, 7, 9, 1, 1)
        self.LineCommand25 = QtWidgets.QLineEdit(Form)
        self.LineCommand25.setObjectName("LineCommand25")
        self.gridLayout.addWidget(self.LineCommand25, 12, 10, 1, 2)
        self.LineName23 = QtWidgets.QLineEdit(Form)
        self.LineName23.setMinimumSize(QtCore.QSize(0, 0))
        self.LineName23.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName23.setObjectName("LineName23")
        self.gridLayout.addWidget(self.LineName23, 10, 9, 1, 1)
        self.LineCommand16 = QtWidgets.QLineEdit(Form)
        self.LineCommand16.setObjectName("LineCommand16")
        self.gridLayout.addWidget(self.LineCommand16, 3, 10, 1, 2)
        self.LineName19 = QtWidgets.QLineEdit(Form)
        self.LineName19.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LineName19.setObjectName("LineName19")
        self.gridLayout.addWidget(self.LineName19, 6, 9, 1, 1)
        self.BtnSend17 = QtWidgets.QPushButton(Form)
        self.BtnSend17.setObjectName("BtnSend17")
        self.gridLayout.addWidget(self.BtnSend17, 4, 12, 1, 1)
        self.LblMacro29 = QtWidgets.QLabel(Form)
        self.LblMacro29.setObjectName("LblMacro29")
        self.gridLayout.addWidget(self.LblMacro29, 16, 8, 1, 1)
        self.LineCommand20 = QtWidgets.QLineEdit(Form)
        self.LineCommand20.setObjectName("LineCommand20")
        self.gridLayout.addWidget(self.LineCommand20, 7, 10, 1, 2)
        self.LineCommand26 = QtWidgets.QLineEdit(Form)
        self.LineCommand26.setObjectName("LineCommand26")
        self.gridLayout.addWidget(self.LineCommand26, 13, 10, 1, 2)
        self.BtnSend21 = QtWidgets.QPushButton(Form)
        self.BtnSend21.setObjectName("BtnSend21")
        self.gridLayout.addWidget(self.BtnSend21, 8, 12, 1, 1)
        self.BtnSend20 = QtWidgets.QPushButton(Form)
        self.BtnSend20.setObjectName("BtnSend20")
        self.gridLayout.addWidget(self.BtnSend20, 7, 12, 1, 1)
        self.BtnSend26 = QtWidgets.QPushButton(Form)
        self.BtnSend26.setObjectName("BtnSend26")
        self.gridLayout.addWidget(self.BtnSend26, 13, 12, 1, 1)
        self.BtnSend29 = QtWidgets.QPushButton(Form)
        self.BtnSend29.setObjectName("BtnSend29")
        self.gridLayout.addWidget(self.BtnSend29, 16, 12, 1, 1)
        self.BtnSend30 = QtWidgets.QPushButton(Form)
        self.BtnSend30.setObjectName("BtnSend30")
        self.gridLayout.addWidget(self.BtnSend30, 17, 12, 1, 1)
        self.BtnSend18 = QtWidgets.QPushButton(Form)
        self.BtnSend18.setObjectName("BtnSend18")
        self.gridLayout.addWidget(self.BtnSend18, 5, 12, 1, 1)
        self.LineCommand18 = QtWidgets.QLineEdit(Form)
        self.LineCommand18.setObjectName("LineCommand18")
        self.gridLayout.addWidget(self.LineCommand18, 5, 10, 1, 2)
        self.BtnSend1 = QtWidgets.QPushButton(Form)
        self.BtnSend1.setObjectName("BtnSend1")
        self.gridLayout.addWidget(self.BtnSend1, 3, 5, 1, 1)
        self.BtnSend25 = QtWidgets.QPushButton(Form)
        self.BtnSend25.setObjectName("BtnSend25")
        self.gridLayout.addWidget(self.BtnSend25, 12, 12, 1, 1)
        self.BtnIcon16 = QtWidgets.QPushButton(Form)
        self.BtnIcon16.setText("")
        self.BtnIcon16.setIcon(icon)
        self.BtnIcon16.setObjectName("BtnIcon16")
        self.gridLayout.addWidget(self.BtnIcon16, 3, 13, 1, 1)
        self.BtnIcon17 = QtWidgets.QPushButton(Form)
        self.BtnIcon17.setText("")
        self.BtnIcon17.setIcon(icon)
        self.BtnIcon17.setObjectName("BtnIcon17")
        self.gridLayout.addWidget(self.BtnIcon17, 4, 13, 1, 1)
        self.BtnIcon18 = QtWidgets.QPushButton(Form)
        self.BtnIcon18.setText("")
        self.BtnIcon18.setIcon(icon)
        self.BtnIcon18.setObjectName("BtnIcon18")
        self.gridLayout.addWidget(self.BtnIcon18, 5, 13, 1, 1)
        self.BtnIcon19 = QtWidgets.QPushButton(Form)
        self.BtnIcon19.setText("")
        self.BtnIcon19.setIcon(icon)
        self.BtnIcon19.setObjectName("BtnIcon19")
        self.gridLayout.addWidget(self.BtnIcon19, 6, 13, 1, 1)
        self.BtnIcon20 = QtWidgets.QPushButton(Form)
        self.BtnIcon20.setText("")
        self.BtnIcon20.setIcon(icon)
        self.BtnIcon20.setObjectName("BtnIcon20")
        self.gridLayout.addWidget(self.BtnIcon20, 7, 13, 1, 1)
        self.BtnIcon21 = QtWidgets.QPushButton(Form)
        self.BtnIcon21.setText("")
        self.BtnIcon21.setIcon(icon)
        self.BtnIcon21.setObjectName("BtnIcon21")
        self.gridLayout.addWidget(self.BtnIcon21, 8, 13, 1, 1)
        self.BtnIcon22 = QtWidgets.QPushButton(Form)
        self.BtnIcon22.setText("")
        self.BtnIcon22.setIcon(icon)
        self.BtnIcon22.setObjectName("BtnIcon22")
        self.gridLayout.addWidget(self.BtnIcon22, 9, 13, 1, 1)
        self.BtnIcon23 = QtWidgets.QPushButton(Form)
        self.BtnIcon23.setText("")
        self.BtnIcon23.setIcon(icon)
        self.BtnIcon23.setObjectName("BtnIcon23")
        self.gridLayout.addWidget(self.BtnIcon23, 10, 13, 1, 1)
        self.BtnIcon24 = QtWidgets.QPushButton(Form)
        self.BtnIcon24.setText("")
        self.BtnIcon24.setIcon(icon)
        self.BtnIcon24.setObjectName("BtnIcon24")
        self.gridLayout.addWidget(self.BtnIcon24, 11, 13, 1, 1)
        self.BtnIcon25 = QtWidgets.QPushButton(Form)
        self.BtnIcon25.setText("")
        self.BtnIcon25.setIcon(icon)
        self.BtnIcon25.setObjectName("BtnIcon25")
        self.gridLayout.addWidget(self.BtnIcon25, 12, 13, 1, 1)
        self.BtnIcon26 = QtWidgets.QPushButton(Form)
        self.BtnIcon26.setText("")
        self.BtnIcon26.setIcon(icon)
        self.BtnIcon26.setObjectName("BtnIcon26")
        self.gridLayout.addWidget(self.BtnIcon26, 13, 13, 1, 1)
        self.BtnIcon27 = QtWidgets.QPushButton(Form)
        self.BtnIcon27.setText("")
        self.BtnIcon27.setIcon(icon)
        self.BtnIcon27.setObjectName("BtnIcon27")
        self.gridLayout.addWidget(self.BtnIcon27, 14, 13, 1, 1)
        self.BtnIcon28 = QtWidgets.QPushButton(Form)
        self.BtnIcon28.setText("")
        self.BtnIcon28.setIcon(icon)
        self.BtnIcon28.setObjectName("BtnIcon28")
        self.gridLayout.addWidget(self.BtnIcon28, 15, 13, 1, 1)
        self.BtnIcon29 = QtWidgets.QPushButton(Form)
        self.BtnIcon29.setText("")
        self.BtnIcon29.setIcon(icon)
        self.BtnIcon29.setObjectName("BtnIcon29")
        self.gridLayout.addWidget(self.BtnIcon29, 16, 13, 1, 1)
        self.BtnIcon30 = QtWidgets.QPushButton(Form)
        self.BtnIcon30.setText("")
        self.BtnIcon30.setIcon(icon)
        self.BtnIcon30.setObjectName("BtnIcon30")
        self.gridLayout.addWidget(self.BtnIcon30, 17, 13, 1, 1)
        self.BtnAdd = QtWidgets.QPushButton(Form)
        self.BtnAdd.setObjectName("BtnAdd")
        self.gridLayout.addWidget(self.BtnAdd, 0, 12, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.LineNameSet, self.LineName1)
        Form.setTabOrder(self.LineName1, self.LineCommand1)
        Form.setTabOrder(self.LineCommand1, self.LineName2)
        Form.setTabOrder(self.LineName2, self.LineCommand2)
        Form.setTabOrder(self.LineCommand2, self.LineName3)
        Form.setTabOrder(self.LineName3, self.LineCommand3)
        Form.setTabOrder(self.LineCommand3, self.LineName4)
        Form.setTabOrder(self.LineName4, self.LineCommand4)
        Form.setTabOrder(self.LineCommand4, self.LineName5)
        Form.setTabOrder(self.LineName5, self.LineCommand5)
        Form.setTabOrder(self.LineCommand5, self.LineName6)
        Form.setTabOrder(self.LineName6, self.LineCommand6)
        Form.setTabOrder(self.LineCommand6, self.LineName7)
        Form.setTabOrder(self.LineName7, self.LineCommand7)
        Form.setTabOrder(self.LineCommand7, self.LineName8)
        Form.setTabOrder(self.LineName8, self.LineCommand8)
        Form.setTabOrder(self.LineCommand8, self.LineName9)
        Form.setTabOrder(self.LineName9, self.LineCommand9)
        Form.setTabOrder(self.LineCommand9, self.LineName10)
        Form.setTabOrder(self.LineName10, self.LineCommand10)
        Form.setTabOrder(self.LineCommand10, self.BtnAll)
        Form.setTabOrder(self.BtnAll, self.BtnSave)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MacrosSet"))
        self.BtnSend27.setText(_translate("Form", "Send"))
        self.BtnSend23.setText(_translate("Form", "Send"))
        self.BtnSend22.setText(_translate("Form", "Send"))
        self.BtnSend28.setText(_translate("Form", "Send"))
        self.BtnSend19.setText(_translate("Form", "Send"))
        self.BtnSend24.setText(_translate("Form", "Send"))
        self.LblMacro7.setText(_translate("Form", "Macro7"))
        self.LblMacro9.setText(_translate("Form", "Macro9"))
        self.LblNameSet.setText(_translate("Form", "Name of Macros Set:"))
        self.LblMacro8.setText(_translate("Form", "Macro8"))
        self.LblMacro2.setText(_translate("Form", "Macro2"))
        self.LblMacro3.setText(_translate("Form", "Macro3"))
        self.LblMacro5.setText(_translate("Form", "Macro5"))
        self.LblCommand2.setText(_translate("Form", "Command:"))
        self.LblMacro6.setText(_translate("Form", "Macro6"))
        self.LblBtnName1.setText(_translate("Form", "Name on Button:"))
        self.BtnSend13.setText(_translate("Form", "Send"))
        self.BtnSend12.setText(_translate("Form", "Send"))
        self.BtnSend8.setText(_translate("Form", "Send"))
        self.LblMacro10.setText(_translate("Form", "Macro10"))
        self.LblMacro21.setText(_translate("Form", "Macro21"))
        self.LblCommmand2.setText(_translate("Form", "Command:"))
        self.LblMacro1.setText(_translate("Form", "Macro1"))
        self.BtnSend14.setText(_translate("Form", "Send"))
        self.BtnSend9.setText(_translate("Form", "Send"))
        self.LblMacro25.setText(_translate("Form", "Macro25"))
        self.LblMacro24.setText(_translate("Form", "Macro24"))
        self.BtnSend2.setText(_translate("Form", "Send"))
        self.BtnSend11.setText(_translate("Form", "Send"))
        self.LblName2.setText(_translate("Form", "Name on Button:"))
        self.LblMacro27.setText(_translate("Form", "Macro27"))
        self.BtnSend4.setText(_translate("Form", "Send"))
        self.BtnSend6.setText(_translate("Form", "Send"))
        self.LblMacro4.setText(_translate("Form", "Macro4"))
        self.BtnSend7.setText(_translate("Form", "Send"))
        self.LblMacro26.setText(_translate("Form", "Macro26"))
        self.LblMacro22.setText(_translate("Form", "Macro22"))
        self.BtnDelete.setText(_translate("Form", "Delete"))
        self.LblMacro14.setText(_translate("Form", "Macro14"))
        self.LblLabel30.setText(_translate("Form", "Macro30"))
        self.BtnSend10.setText(_translate("Form", "Send"))
        self.LblMacro28.setText(_translate("Form", "Macro28"))
        self.BtnSend15.setText(_translate("Form", "Send"))
        self.LblMacro15.setText(_translate("Form", "Macro15"))
        self.BtnSend3.setText(_translate("Form", "Send"))
        self.LblMacro20.setText(_translate("Form", "Macro20"))
        self.LblMacro23.setText(_translate("Form", "Macro23"))
        self.LblMacro12.setText(_translate("Form", "Macro12"))
        self.LblMacro11.setText(_translate("Form", "Macro11"))
        self.LblMacro16.setText(_translate("Form", "Macro16"))
        self.LblMacro18.setText(_translate("Form", "Macro18"))
        self.BtnSend5.setText(_translate("Form", "Send"))
        self.LblMacro19.setText(_translate("Form", "Macro19"))
        self.BtnAll.setText(_translate("Form", "Save and Apply"))
        self.BtnSave.setText(_translate("Form", "Save only"))
        self.LblMacro13.setText(_translate("Form", "Macro13"))
        self.BtnSend16.setText(_translate("Form", "Send"))
        self.LblMacro17.setText(_translate("Form", "Macro17"))
        self.BtnSend17.setText(_translate("Form", "Send"))
        self.LblMacro29.setText(_translate("Form", "Macro29"))
        self.BtnSend21.setText(_translate("Form", "Send"))
        self.BtnSend20.setText(_translate("Form", "Send"))
        self.BtnSend26.setText(_translate("Form", "Send"))
        self.BtnSend29.setText(_translate("Form", "Send"))
        self.BtnSend30.setText(_translate("Form", "Send"))
        self.BtnSend18.setText(_translate("Form", "Send"))
        self.BtnSend1.setText(_translate("Form", "Send"))
        self.BtnSend25.setText(_translate("Form", "Send"))
        self.BtnAdd.setText(_translate("Form", "Add New"))

import logo_rc
