# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(437, 442)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.CBEndLine = QtWidgets.QCheckBox(Form)
        self.CBEndLine.setChecked(True)
        self.CBEndLine.setObjectName("CBEndLine")
        self.gridLayout.addWidget(self.CBEndLine, 2, 0, 1, 1)
        self.GBParity = QtWidgets.QGroupBox(Form)
        self.GBParity.setObjectName("GBParity")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.GBParity)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.RBParityMark = QtWidgets.QRadioButton(self.GBParity)
        self.RBParityMark.setObjectName("RBParityMark")
        self.gridLayout_3.addWidget(self.RBParityMark, 3, 0, 1, 1)
        self.RBParityNone = QtWidgets.QRadioButton(self.GBParity)
        self.RBParityNone.setChecked(True)
        self.RBParityNone.setObjectName("RBParityNone")
        self.gridLayout_3.addWidget(self.RBParityNone, 0, 0, 1, 1)
        self.RBParityOdd = QtWidgets.QRadioButton(self.GBParity)
        self.RBParityOdd.setObjectName("RBParityOdd")
        self.gridLayout_3.addWidget(self.RBParityOdd, 1, 0, 1, 1)
        self.RBParityEven = QtWidgets.QRadioButton(self.GBParity)
        self.RBParityEven.setObjectName("RBParityEven")
        self.gridLayout_3.addWidget(self.RBParityEven, 2, 0, 1, 1)
        self.RBParitySpace = QtWidgets.QRadioButton(self.GBParity)
        self.RBParitySpace.setObjectName("RBParitySpace")
        self.gridLayout_3.addWidget(self.RBParitySpace, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.GBParity, 0, 1, 2, 1)
        self.GBDatabits = QtWidgets.QGroupBox(Form)
        self.GBDatabits.setCheckable(False)
        self.GBDatabits.setObjectName("GBDatabits")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.GBDatabits)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.RBDatabits6 = QtWidgets.QRadioButton(self.GBDatabits)
        self.RBDatabits6.setObjectName("RBDatabits6")
        self.gridLayout_2.addWidget(self.RBDatabits6, 2, 0, 1, 1)
        self.RBDatabits5 = QtWidgets.QRadioButton(self.GBDatabits)
        self.RBDatabits5.setObjectName("RBDatabits5")
        self.gridLayout_2.addWidget(self.RBDatabits5, 1, 0, 1, 1)
        self.RBDatabits7 = QtWidgets.QRadioButton(self.GBDatabits)
        self.RBDatabits7.setObjectName("RBDatabits7")
        self.gridLayout_2.addWidget(self.RBDatabits7, 3, 0, 1, 1)
        self.RBDatabits8 = QtWidgets.QRadioButton(self.GBDatabits)
        self.RBDatabits8.setChecked(True)
        self.RBDatabits8.setObjectName("RBDatabits8")
        self.gridLayout_2.addWidget(self.RBDatabits8, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.GBDatabits, 0, 0, 2, 1)
        self.GBStopBits = QtWidgets.QGroupBox(Form)
        self.GBStopBits.setObjectName("GBStopBits")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.GBStopBits)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.RBStopbits1 = QtWidgets.QRadioButton(self.GBStopBits)
        self.RBStopbits1.setObjectName("RBStopbits1")
        self.gridLayout_4.addWidget(self.RBStopbits1, 0, 0, 1, 1)
        self.RBStopbits15 = QtWidgets.QRadioButton(self.GBStopBits)
        self.RBStopbits15.setObjectName("RBStopbits15")
        self.gridLayout_4.addWidget(self.RBStopbits15, 1, 0, 1, 1)
        self.RBStopbits2 = QtWidgets.QRadioButton(self.GBStopBits)
        self.RBStopbits2.setObjectName("RBStopbits2")
        self.gridLayout_4.addWidget(self.RBStopbits2, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.GBStopBits, 0, 2, 1, 1)
        self.GBHandshaking = QtWidgets.QGroupBox(Form)
        self.GBHandshaking.setObjectName("GBHandshaking")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.GBHandshaking)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.RBHandNone = QtWidgets.QRadioButton(self.GBHandshaking)
        self.RBHandNone.setObjectName("RBHandNone")
        self.gridLayout_5.addWidget(self.RBHandNone, 0, 0, 1, 1)
        self.RBHandRts = QtWidgets.QRadioButton(self.GBHandshaking)
        self.RBHandRts.setObjectName("RBHandRts")
        self.gridLayout_5.addWidget(self.RBHandRts, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.GBHandshaking, 1, 2, 1, 1)
        self.GBColor = QtWidgets.QGroupBox(Form)
        self.GBColor.setObjectName("GBColor")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.GBColor)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.BtnFont = QtWidgets.QPushButton(self.GBColor)
        self.BtnFont.setObjectName("BtnFont")
        self.gridLayout_6.addWidget(self.BtnFont, 0, 0, 1, 3)
        self.LblFont = QtWidgets.QLabel(self.GBColor)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.LblFont.setFont(font)
        self.LblFont.setObjectName("LblFont")
        self.gridLayout_6.addWidget(self.LblFont, 0, 3, 1, 1)
        self.GBBackColor = QtWidgets.QGroupBox(self.GBColor)
        self.GBBackColor.setObjectName("GBBackColor")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.GBBackColor)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.LblBackgroundColor = QtWidgets.QLabel(self.GBBackColor)
        self.LblBackgroundColor.setStyleSheet("background-color: rgb(255,255,255)")
        self.LblBackgroundColor.setText("")
        self.LblBackgroundColor.setObjectName("LblBackgroundColor")
        self.gridLayout_7.addWidget(self.LblBackgroundColor, 0, 0, 1, 1)
        self.BtnBackgroundColor = QtWidgets.QPushButton(self.GBBackColor)
        self.BtnBackgroundColor.setObjectName("BtnBackgroundColor")
        self.gridLayout_7.addWidget(self.BtnBackgroundColor, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.GBBackColor, 1, 0, 2, 1)
        self.GBReceived = QtWidgets.QGroupBox(self.GBColor)
        self.GBReceived.setObjectName("GBReceived")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.GBReceived)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.LblReceivedColor = QtWidgets.QLabel(self.GBReceived)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.LblReceivedColor.setFont(font)
        self.LblReceivedColor.setStyleSheet("background-color: white")
        self.LblReceivedColor.setObjectName("LblReceivedColor")
        self.gridLayout_9.addWidget(self.LblReceivedColor, 0, 0, 1, 1)
        self.BtnReceivedColor = QtWidgets.QPushButton(self.GBReceived)
        self.BtnReceivedColor.setObjectName("BtnReceivedColor")
        self.gridLayout_9.addWidget(self.BtnReceivedColor, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.GBReceived, 1, 3, 2, 1)
        self.GBSent = QtWidgets.QGroupBox(self.GBColor)
        self.GBSent.setObjectName("GBSent")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.GBSent)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.LblSentColor = QtWidgets.QLabel(self.GBSent)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.LblSentColor.setFont(font)
        self.LblSentColor.setStyleSheet("background-color: rgb(255,255,255); color: rgb(00,102,51)")
        self.LblSentColor.setObjectName("LblSentColor")
        self.gridLayout_8.addWidget(self.LblSentColor, 0, 0, 1, 1)
        self.BtnSentColor = QtWidgets.QPushButton(self.GBSent)
        self.BtnSentColor.setObjectName("BtnSentColor")
        self.gridLayout_8.addWidget(self.BtnSentColor, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.GBSent, 1, 1, 2, 2)
        self.gridLayout.addWidget(self.GBColor, 3, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.RBDatabits5, self.RBDatabits6)
        Form.setTabOrder(self.RBDatabits6, self.RBDatabits7)
        Form.setTabOrder(self.RBDatabits7, self.RBDatabits8)
        Form.setTabOrder(self.RBDatabits8, self.RBParityNone)
        Form.setTabOrder(self.RBParityNone, self.RBParityOdd)
        Form.setTabOrder(self.RBParityOdd, self.RBParityEven)
        Form.setTabOrder(self.RBParityEven, self.RBParityMark)
        Form.setTabOrder(self.RBParityMark, self.RBParitySpace)
        Form.setTabOrder(self.RBParitySpace, self.RBStopbits1)
        Form.setTabOrder(self.RBStopbits1, self.RBStopbits15)
        Form.setTabOrder(self.RBStopbits15, self.RBStopbits2)
        Form.setTabOrder(self.RBStopbits2, self.RBHandNone)
        Form.setTabOrder(self.RBHandNone, self.RBHandRts)
        Form.setTabOrder(self.RBHandRts, self.CBEndLine)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Settings"))
        self.CBEndLine.setText(_translate("Form", "Add CR/LF"))
        self.GBParity.setTitle(_translate("Form", "Parity"))
        self.RBParityMark.setText(_translate("Form", "Mark"))
        self.RBParityNone.setText(_translate("Form", "None"))
        self.RBParityOdd.setText(_translate("Form", "Odd"))
        self.RBParityEven.setText(_translate("Form", "Even"))
        self.RBParitySpace.setText(_translate("Form", "Space"))
        self.GBDatabits.setTitle(_translate("Form", "Data bits"))
        self.RBDatabits6.setText(_translate("Form", "6"))
        self.RBDatabits5.setText(_translate("Form", "5"))
        self.RBDatabits7.setText(_translate("Form", "7"))
        self.RBDatabits8.setText(_translate("Form", "8"))
        self.GBStopBits.setTitle(_translate("Form", "Stop bits"))
        self.RBStopbits1.setText(_translate("Form", "1"))
        self.RBStopbits15.setText(_translate("Form", "1.5"))
        self.RBStopbits2.setText(_translate("Form", "2"))
        self.GBHandshaking.setTitle(_translate("Form", "Handshaking"))
        self.RBHandNone.setText(_translate("Form", "None"))
        self.RBHandRts.setText(_translate("Form", "RTS/CTS"))
        self.GBColor.setTitle(_translate("Form", "Select TextField Style"))
        self.BtnFont.setText(_translate("Form", "Select Font Style"))
        self.LblFont.setText(_translate("Form", "Font  Style"))
        self.GBBackColor.setTitle(_translate("Form", "Background color"))
        self.BtnBackgroundColor.setText(_translate("Form", "Select Color"))
        self.GBReceived.setTitle(_translate("Form", "Font Received Color"))
        self.LblReceivedColor.setText(_translate("Form", "Received"))
        self.BtnReceivedColor.setText(_translate("Form", "Select Color"))
        self.GBSent.setTitle(_translate("Form", "Font Sent Color"))
        self.LblSentColor.setText(_translate("Form", "Sent"))
        self.BtnSentColor.setText(_translate("Form", "Select Color"))

