# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(368, 257)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.GBParity = QtWidgets.QGroupBox(Form)
        self.GBParity.setObjectName("GBParity")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.GBParity)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.RBParityMark = QtWidgets.QRadioButton(self.GBParity)
        self.RBParityMark.setObjectName("RBParityMark")
        self.gridLayout_3.addWidget(self.RBParityMark, 3, 0, 1, 1)
        self.RBParityNone = QtWidgets.QRadioButton(self.GBParity)
        self.RBParityNone.setChecked(True)
        self.RBParityNone.setObjectName("RBParityNone")
        self.gridLayout_3.addWidget(self.RBParityNone, 0, 0, 1, 1)
        self.RBParityOdd = QtWidgets.QRadioButton(self.GBParity)
        self.RBParityOdd.setObjectName("RBParityOdd")
        self.gridLayout_3.addWidget(self.RBParityOdd, 1, 0, 1, 1)
        self.RBParityEven = QtWidgets.QRadioButton(self.GBParity)
        self.RBParityEven.setObjectName("RBParityEven")
        self.gridLayout_3.addWidget(self.RBParityEven, 2, 0, 1, 1)
        self.RBParitySpace = QtWidgets.QRadioButton(self.GBParity)
        self.RBParitySpace.setObjectName("RBParitySpace")
        self.gridLayout_3.addWidget(self.RBParitySpace, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.GBParity, 0, 1, 2, 1)
        self.GBDatabits = QtWidgets.QGroupBox(Form)
        self.GBDatabits.setObjectName("GBDatabits")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.GBDatabits)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.RBDatabits7 = QtWidgets.QRadioButton(self.GBDatabits)
        self.RBDatabits7.setObjectName("RBDatabits7")
        self.gridLayout_2.addWidget(self.RBDatabits7, 2, 0, 1, 1)
        self.RBDatabits8 = QtWidgets.QRadioButton(self.GBDatabits)
        self.RBDatabits8.setChecked(True)
        self.RBDatabits8.setObjectName("RBDatabits8")
        self.gridLayout_2.addWidget(self.RBDatabits8, 3, 0, 1, 1)
        self.RBDatabits5 = QtWidgets.QRadioButton(self.GBDatabits)
        self.RBDatabits5.setObjectName("RBDatabits5")
        self.gridLayout_2.addWidget(self.RBDatabits5, 0, 0, 1, 1)
        self.RBDatabits6 = QtWidgets.QRadioButton(self.GBDatabits)
        self.RBDatabits6.setObjectName("RBDatabits6")
        self.gridLayout_2.addWidget(self.RBDatabits6, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.GBDatabits, 0, 0, 2, 1)
        self.GBStopBits = QtWidgets.QGroupBox(Form)
        self.GBStopBits.setObjectName("GBStopBits")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.GBStopBits)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.RBStopbits1 = QtWidgets.QRadioButton(self.GBStopBits)
        self.RBStopbits1.setObjectName("RBStopbits1")
        self.gridLayout_4.addWidget(self.RBStopbits1, 0, 0, 1, 1)
        self.RBStopbits15 = QtWidgets.QRadioButton(self.GBStopBits)
        self.RBStopbits15.setObjectName("RBStopbits15")
        self.gridLayout_4.addWidget(self.RBStopbits15, 1, 0, 1, 1)
        self.RBStopbits2 = QtWidgets.QRadioButton(self.GBStopBits)
        self.RBStopbits2.setObjectName("RBStopbits2")
        self.gridLayout_4.addWidget(self.RBStopbits2, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.GBStopBits, 0, 2, 1, 1)
        self.GBHandshaking = QtWidgets.QGroupBox(Form)
        self.GBHandshaking.setObjectName("GBHandshaking")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.GBHandshaking)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.RBHandNone = QtWidgets.QRadioButton(self.GBHandshaking)
        self.RBHandNone.setObjectName("RBHandNone")
        self.gridLayout_5.addWidget(self.RBHandNone, 0, 0, 1, 1)
        self.RBHandRts = QtWidgets.QRadioButton(self.GBHandshaking)
        self.RBHandRts.setObjectName("RBHandRts")
        self.gridLayout_5.addWidget(self.RBHandRts, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.GBHandshaking, 1, 2, 1, 1)
        self.CBEndLine = QtWidgets.QCheckBox(Form)
        self.CBEndLine.setObjectName("CBEndLine")
        self.gridLayout.addWidget(self.CBEndLine, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Settings"))
        self.GBParity.setTitle(_translate("Form", "Parity"))
        self.RBParityMark.setText(_translate("Form", "Mark"))
        self.RBParityNone.setText(_translate("Form", "None"))
        self.RBParityOdd.setText(_translate("Form", "Odd"))
        self.RBParityEven.setText(_translate("Form", "Even"))
        self.RBParitySpace.setText(_translate("Form", "Space"))
        self.GBDatabits.setTitle(_translate("Form", "Data bits"))
        self.RBDatabits7.setText(_translate("Form", "7"))
        self.RBDatabits8.setText(_translate("Form", "8"))
        self.RBDatabits5.setText(_translate("Form", "5"))
        self.RBDatabits6.setText(_translate("Form", "6"))
        self.GBStopBits.setTitle(_translate("Form", "Stop bits"))
        self.RBStopbits1.setText(_translate("Form", "1"))
        self.RBStopbits15.setText(_translate("Form", "1.5"))
        self.RBStopbits2.setText(_translate("Form", "2"))
        self.GBHandshaking.setTitle(_translate("Form", "Handshaking"))
        self.RBHandNone.setText(_translate("Form", "None"))
        self.RBHandRts.setText(_translate("Form", "RTS/CTS"))
        self.CBEndLine.setText(_translate("Form", "Add CR/LF"))

