# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Terminal.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 310)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.TxtBuffer = QtWidgets.QTextBrowser(self.centralwidget)
        self.TxtBuffer.setObjectName("TxtBuffer")
        self.gridLayout.addWidget(self.TxtBuffer, 1, 3, 11, 5)
        self.BtnClear = QtWidgets.QPushButton(self.centralwidget)
        self.BtnClear.setObjectName("BtnClear")
        self.gridLayout.addWidget(self.BtnClear, 0, 7, 1, 1)
        self.LblTransmit = QtWidgets.QLabel(self.centralwidget)
        self.LblTransmit.setObjectName("LblTransmit")
        self.gridLayout.addWidget(self.LblTransmit, 12, 1, 1, 1, QtCore.Qt.AlignRight)
        self.BtnSend = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSend.setEnabled(False)
        self.BtnSend.setObjectName("BtnSend")
        self.gridLayout.addWidget(self.BtnSend, 12, 7, 1, 1)
        self.LblCounter = QtWidgets.QLabel(self.centralwidget)
        self.LblCounter.setMaximumSize(QtCore.QSize(55, 16777215))
        self.LblCounter.setObjectName("LblCounter")
        self.gridLayout.addWidget(self.LblCounter, 0, 3, 1, 1)
        self.CBSTM = QtWidgets.QCheckBox(self.centralwidget)
        self.CBSTM.setObjectName("CBSTM")
        self.gridLayout.addWidget(self.CBSTM, 5, 1, 1, 1)
        self.CBBaudrate = QtWidgets.QComboBox(self.centralwidget)
        self.CBBaudrate.setObjectName("CBBaudrate")
        self.CBBaudrate.addItem("")
        self.CBBaudrate.addItem("")
        self.CBBaudrate.addItem("")
        self.CBBaudrate.addItem("")
        self.gridLayout.addWidget(self.CBBaudrate, 8, 1, 1, 1)
        self.LblStatusInfo = QtWidgets.QLabel(self.centralwidget)
        self.LblStatusInfo.setObjectName("LblStatusInfo")
        self.gridLayout.addWidget(self.LblStatusInfo, 7, 1, 1, 1)
        self.BtnReScan = QtWidgets.QPushButton(self.centralwidget)
        self.BtnReScan.setObjectName("BtnReScan")
        self.gridLayout.addWidget(self.BtnReScan, 5, 0, 1, 1)
        self.LblAvailable = QtWidgets.QLabel(self.centralwidget)
        self.LblAvailable.setObjectName("LblAvailable")
        self.gridLayout.addWidget(self.LblAvailable, 1, 0, 1, 1)
        self.LblStatus = QtWidgets.QLabel(self.centralwidget)
        self.LblStatus.setObjectName("LblStatus")
        self.gridLayout.addWidget(self.LblStatus, 7, 0, 1, 1)
        self.CBPorts = QtWidgets.QComboBox(self.centralwidget)
        self.CBPorts.setMinimumSize(QtCore.QSize(300, 0))
        self.CBPorts.setObjectName("CBPorts")
        self.gridLayout.addWidget(self.CBPorts, 2, 0, 1, 2)
        self.BtnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.BtnConnect.setEnabled(False)
        self.BtnConnect.setObjectName("BtnConnect")
        self.gridLayout.addWidget(self.BtnConnect, 9, 0, 1, 1)
        self.BtnDisconnect = QtWidgets.QPushButton(self.centralwidget)
        self.BtnDisconnect.setEnabled(False)
        self.BtnDisconnect.setObjectName("BtnDisconnect")
        self.gridLayout.addWidget(self.BtnDisconnect, 9, 1, 1, 1)
        self.LblBaudrate = QtWidgets.QLabel(self.centralwidget)
        self.LblBaudrate.setObjectName("LblBaudrate")
        self.gridLayout.addWidget(self.LblBaudrate, 8, 0, 1, 1)
        self.TxtTransmit = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtTransmit.setObjectName("TxtTransmit")
        self.gridLayout.addWidget(self.TxtTransmit, 12, 3, 1, 4)
        self.BtnCounter = QtWidgets.QPushButton(self.centralwidget)
        self.BtnCounter.setObjectName("BtnCounter")
        self.gridLayout.addWidget(self.BtnCounter, 0, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        self.LblCounterData = QtWidgets.QLabel(self.centralwidget)
        self.LblCounterData.setObjectName("LblCounterData")
        self.gridLayout.addWidget(self.LblCounterData, 0, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OstrannaTerminal"))
        self.BtnClear.setText(_translate("MainWindow", "Clear"))
        self.LblTransmit.setText(_translate("MainWindow", "Transmit:"))
        self.BtnSend.setText(_translate("MainWindow", "Send"))
        self.LblCounter.setText(_translate("MainWindow", "Counter:"))
        self.CBSTM.setText(_translate("MainWindow", "STM devices only"))
        self.CBBaudrate.setItemText(0, _translate("MainWindow", "9600"))
        self.CBBaudrate.setItemText(1, _translate("MainWindow", "115200"))
        self.CBBaudrate.setItemText(2, _translate("MainWindow", "256000"))
        self.CBBaudrate.setItemText(3, _translate("MainWindow", "Custom"))
        self.LblStatusInfo.setText(_translate("MainWindow", "Not Connected"))
        self.BtnReScan.setText(_translate("MainWindow", "ReScan"))
        self.LblAvailable.setText(_translate("MainWindow", "COMs Available:"))
        self.LblStatus.setText(_translate("MainWindow", "Status:"))
        self.BtnConnect.setText(_translate("MainWindow", "Connect"))
        self.BtnDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.LblBaudrate.setText(_translate("MainWindow", "Baudrate:"))
        self.BtnCounter.setText(_translate("MainWindow", "Clear Counter"))
        self.LblCounterData.setText(_translate("MainWindow", "0"))

