# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Terminal.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1424, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.TxtBuffer = QtWidgets.QTextBrowser(self.centralwidget)
        self.TxtBuffer.setObjectName("TxtBuffer")
        self.gridLayout.addWidget(self.TxtBuffer, 10, 0, 1, 13)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.LblBaudrate = QtWidgets.QLabel(self.groupBox_2)
        self.LblBaudrate.setObjectName("LblBaudrate")
        self.gridLayout_3.addWidget(self.LblBaudrate, 2, 0, 1, 1)
        self.CBBaudrate = QtWidgets.QComboBox(self.groupBox_2)
        self.CBBaudrate.setObjectName("CBBaudrate")
        self.CBBaudrate.addItem("")
        self.CBBaudrate.addItem("")
        self.CBBaudrate.addItem("")
        self.CBBaudrate.addItem("")
        self.gridLayout_3.addWidget(self.CBBaudrate, 2, 1, 1, 2)
        self.BtnSettings = QtWidgets.QPushButton(self.groupBox_2)
        self.BtnSettings.setObjectName("BtnSettings")
        self.gridLayout_3.addWidget(self.BtnSettings, 0, 0, 1, 3)
        self.gridLayout.addWidget(self.groupBox_2, 4, 13, 5, 2)
        self.BtnBuffer = QtWidgets.QPushButton(self.centralwidget)
        self.BtnBuffer.setEnabled(False)
        self.BtnBuffer.setObjectName("BtnBuffer")
        self.gridLayout.addWidget(self.BtnBuffer, 7, 12, 1, 1)
        self.BtnSave = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSave.setObjectName("BtnSave")
        self.gridLayout.addWidget(self.BtnSave, 8, 12, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.LblMacrosSelected = QtWidgets.QLabel(self.groupBox_5)
        self.LblMacrosSelected.setObjectName("LblMacrosSelected")
        self.gridLayout_6.addWidget(self.LblMacrosSelected, 12, 0, 1, 2)
        self.BtnMacros11 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros11.setEnabled(False)
        self.BtnMacros11.setObjectName("BtnMacros11")
        self.gridLayout_6.addWidget(self.BtnMacros11, 0, 1, 1, 1)
        self.BtnMacros12 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros12.setEnabled(False)
        self.BtnMacros12.setObjectName("BtnMacros12")
        self.gridLayout_6.addWidget(self.BtnMacros12, 1, 1, 1, 1)
        self.BtnMacros14 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros14.setEnabled(False)
        self.BtnMacros14.setObjectName("BtnMacros14")
        self.gridLayout_6.addWidget(self.BtnMacros14, 3, 1, 1, 1)
        self.BtnMacros2 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros2.setEnabled(False)
        self.BtnMacros2.setObjectName("BtnMacros2")
        self.gridLayout_6.addWidget(self.BtnMacros2, 1, 0, 1, 1)
        self.BtnMacros5 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros5.setEnabled(False)
        self.BtnMacros5.setObjectName("BtnMacros5")
        self.gridLayout_6.addWidget(self.BtnMacros5, 4, 0, 1, 1)
        self.BtnMacros15 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros15.setEnabled(False)
        self.BtnMacros15.setObjectName("BtnMacros15")
        self.gridLayout_6.addWidget(self.BtnMacros15, 4, 1, 1, 1)
        self.BtnMacros17 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros17.setEnabled(False)
        self.BtnMacros17.setObjectName("BtnMacros17")
        self.gridLayout_6.addWidget(self.BtnMacros17, 6, 1, 1, 1)
        self.BtnMacros16 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros16.setEnabled(False)
        self.BtnMacros16.setObjectName("BtnMacros16")
        self.gridLayout_6.addWidget(self.BtnMacros16, 5, 1, 1, 1)
        self.BtnMacros8 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros8.setEnabled(False)
        self.BtnMacros8.setObjectName("BtnMacros8")
        self.gridLayout_6.addWidget(self.BtnMacros8, 7, 0, 1, 1)
        self.BtnMacros9 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros9.setEnabled(False)
        self.BtnMacros9.setObjectName("BtnMacros9")
        self.gridLayout_6.addWidget(self.BtnMacros9, 8, 0, 1, 1)
        self.BtnMacros6 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros6.setEnabled(False)
        self.BtnMacros6.setObjectName("BtnMacros6")
        self.gridLayout_6.addWidget(self.BtnMacros6, 5, 0, 1, 1)
        self.BtnMacros7 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros7.setEnabled(False)
        self.BtnMacros7.setObjectName("BtnMacros7")
        self.gridLayout_6.addWidget(self.BtnMacros7, 6, 0, 1, 1)
        self.BtnMacros20 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros20.setEnabled(False)
        self.BtnMacros20.setObjectName("BtnMacros20")
        self.gridLayout_6.addWidget(self.BtnMacros20, 9, 1, 1, 1)
        self.CBMacros = QtWidgets.QComboBox(self.groupBox_5)
        self.CBMacros.setObjectName("CBMacros")
        self.gridLayout_6.addWidget(self.CBMacros, 11, 0, 1, 2)
        self.BtnMacros18 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros18.setEnabled(False)
        self.BtnMacros18.setObjectName("BtnMacros18")
        self.gridLayout_6.addWidget(self.BtnMacros18, 7, 1, 1, 1)
        self.BtnMacros19 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros19.setEnabled(False)
        self.BtnMacros19.setObjectName("BtnMacros19")
        self.gridLayout_6.addWidget(self.BtnMacros19, 8, 1, 1, 1)
        self.BtnMacros10 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros10.setEnabled(False)
        self.BtnMacros10.setObjectName("BtnMacros10")
        self.gridLayout_6.addWidget(self.BtnMacros10, 9, 0, 1, 1)
        self.LblMacrosAvailable = QtWidgets.QLabel(self.groupBox_5)
        self.LblMacrosAvailable.setObjectName("LblMacrosAvailable")
        self.gridLayout_6.addWidget(self.LblMacrosAvailable, 10, 0, 1, 2)
        self.BtnMacros1 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros1.setEnabled(False)
        self.BtnMacros1.setObjectName("BtnMacros1")
        self.gridLayout_6.addWidget(self.BtnMacros1, 0, 0, 1, 1)
        self.BtnMacros4 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros4.setEnabled(False)
        self.BtnMacros4.setObjectName("BtnMacros4")
        self.gridLayout_6.addWidget(self.BtnMacros4, 3, 0, 1, 1)
        self.BtnMacros3 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros3.setEnabled(False)
        self.BtnMacros3.setObjectName("BtnMacros3")
        self.gridLayout_6.addWidget(self.BtnMacros3, 2, 0, 1, 1)
        self.BtnMacros13 = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnMacros13.setEnabled(False)
        self.BtnMacros13.setObjectName("BtnMacros13")
        self.gridLayout_6.addWidget(self.BtnMacros13, 2, 1, 1, 1)
        self.BtnCreateMacros = QtWidgets.QPushButton(self.groupBox_5)
        self.BtnCreateMacros.setObjectName("BtnCreateMacros")
        self.gridLayout_6.addWidget(self.BtnCreateMacros, 13, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_5, 10, 13, 3, 2)
        self.LblAvailable = QtWidgets.QLabel(self.centralwidget)
        self.LblAvailable.setObjectName("LblAvailable")
        self.gridLayout.addWidget(self.LblAvailable, 5, 1, 1, 1)
        self.CBPorts = QtWidgets.QComboBox(self.centralwidget)
        self.CBPorts.setMinimumSize(QtCore.QSize(300, 0))
        self.CBPorts.setObjectName("CBPorts")
        self.gridLayout.addWidget(self.CBPorts, 7, 1, 1, 4)
        self.LblStatusInfo = QtWidgets.QLabel(self.centralwidget)
        self.LblStatusInfo.setObjectName("LblStatusInfo")
        self.gridLayout.addWidget(self.LblStatusInfo, 8, 2, 1, 1)
        self.LblTransmit = QtWidgets.QLabel(self.centralwidget)
        self.LblTransmit.setObjectName("LblTransmit")
        self.gridLayout.addWidget(self.LblTransmit, 28, 0, 1, 1, QtCore.Qt.AlignRight)
        self.LblStatus = QtWidgets.QLabel(self.centralwidget)
        self.LblStatus.setObjectName("LblStatus")
        self.gridLayout.addWidget(self.LblStatus, 8, 1, 1, 1)
        self.TxtTransmit = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtTransmit.setObjectName("TxtTransmit")
        self.gridLayout.addWidget(self.TxtTransmit, 28, 1, 1, 8)
        self.BtnSend = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSend.setEnabled(False)
        self.BtnSend.setObjectName("BtnSend")
        self.gridLayout.addWidget(self.BtnSend, 28, 9, 1, 1)
        self.CBSTM = QtWidgets.QCheckBox(self.centralwidget)
        self.CBSTM.setChecked(True)
        self.CBSTM.setObjectName("CBSTM")
        self.gridLayout.addWidget(self.CBSTM, 8, 4, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.CBScroll = QtWidgets.QCheckBox(self.groupBox_4)
        self.CBScroll.setChecked(True)
        self.CBScroll.setObjectName("CBScroll")
        self.gridLayout_5.addWidget(self.CBScroll, 0, 1, 1, 1)
        self.CBTime = QtWidgets.QCheckBox(self.groupBox_4)
        self.CBTime.setObjectName("CBTime")
        self.gridLayout_5.addWidget(self.CBTime, 0, 0, 1, 1)
        self.CBShowSent = QtWidgets.QCheckBox(self.groupBox_4)
        self.CBShowSent.setChecked(True)
        self.CBShowSent.setObjectName("CBShowSent")
        self.gridLayout_5.addWidget(self.CBShowSent, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 7, 10, 2, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 8, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BtnReScan = QtWidgets.QPushButton(self.groupBox)
        self.BtnReScan.setObjectName("BtnReScan")
        self.gridLayout_2.addWidget(self.BtnReScan, 0, 0, 1, 1)
        self.BtnConnect = QtWidgets.QPushButton(self.groupBox)
        self.BtnConnect.setEnabled(False)
        self.BtnConnect.setObjectName("BtnConnect")
        self.gridLayout_2.addWidget(self.BtnConnect, 0, 1, 1, 1)
        self.BtnClear = QtWidgets.QPushButton(self.groupBox)
        self.BtnClear.setObjectName("BtnClear")
        self.gridLayout_2.addWidget(self.BtnClear, 1, 0, 1, 1)
        self.BtnDisconnect = QtWidgets.QPushButton(self.groupBox)
        self.BtnDisconnect.setEnabled(False)
        self.BtnDisconnect.setObjectName("BtnDisconnect")
        self.gridLayout_2.addWidget(self.BtnDisconnect, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 6, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.LblCounter = QtWidgets.QLabel(self.groupBox_3)
        self.LblCounter.setMaximumSize(QtCore.QSize(55, 16777215))
        self.LblCounter.setObjectName("LblCounter")
        self.gridLayout_4.addWidget(self.LblCounter, 0, 0, 1, 1)
        self.BtnCounter = QtWidgets.QPushButton(self.groupBox_3)
        self.BtnCounter.setObjectName("BtnCounter")
        self.gridLayout_4.addWidget(self.BtnCounter, 0, 2, 1, 1)
        self.LblCounterData = QtWidgets.QLabel(self.groupBox_3)
        self.LblCounterData.setObjectName("LblCounterData")
        self.gridLayout_4.addWidget(self.LblCounterData, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 7, 7, 2, 3)
        self.CBClear = QtWidgets.QCheckBox(self.centralwidget)
        self.CBClear.setChecked(True)
        self.CBClear.setObjectName("CBClear")
        self.gridLayout.addWidget(self.CBClear, 28, 10, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_7.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_6, 28, 11, 2, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OstrannaTerminal"))
        self.TxtBuffer.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Settings "))
        self.LblBaudrate.setText(_translate("MainWindow", "Baudrate:"))
        self.CBBaudrate.setItemText(0, _translate("MainWindow", "9600"))
        self.CBBaudrate.setItemText(1, _translate("MainWindow", "115200"))
        self.CBBaudrate.setItemText(2, _translate("MainWindow", "256000"))
        self.CBBaudrate.setItemText(3, _translate("MainWindow", "Custom"))
        self.BtnSettings.setText(_translate("MainWindow", "Settings"))
        self.BtnBuffer.setText(_translate("MainWindow", "Read Buffer"))
        self.BtnSave.setText(_translate("MainWindow", "Save to log"))
        self.groupBox_5.setTitle(_translate("MainWindow", "GroupBox"))
        self.LblMacrosSelected.setText(_translate("MainWindow", "Macros set selected: None"))
        self.BtnMacros11.setText(_translate("MainWindow", "M11"))
        self.BtnMacros12.setText(_translate("MainWindow", "M12"))
        self.BtnMacros14.setText(_translate("MainWindow", "M14"))
        self.BtnMacros2.setText(_translate("MainWindow", "M2"))
        self.BtnMacros5.setText(_translate("MainWindow", "M5"))
        self.BtnMacros15.setText(_translate("MainWindow", "M15"))
        self.BtnMacros17.setText(_translate("MainWindow", "M17"))
        self.BtnMacros16.setText(_translate("MainWindow", "M16"))
        self.BtnMacros8.setText(_translate("MainWindow", "M8"))
        self.BtnMacros9.setText(_translate("MainWindow", "M9"))
        self.BtnMacros6.setText(_translate("MainWindow", "M6"))
        self.BtnMacros7.setText(_translate("MainWindow", "M7"))
        self.BtnMacros20.setText(_translate("MainWindow", "M20"))
        self.BtnMacros18.setText(_translate("MainWindow", "M18"))
        self.BtnMacros19.setText(_translate("MainWindow", "M19"))
        self.BtnMacros10.setText(_translate("MainWindow", "M10"))
        self.LblMacrosAvailable.setText(_translate("MainWindow", "Macros sets available"))
        self.BtnMacros1.setText(_translate("MainWindow", "M1"))
        self.BtnMacros4.setText(_translate("MainWindow", "M4"))
        self.BtnMacros3.setText(_translate("MainWindow", "M3"))
        self.BtnMacros13.setText(_translate("MainWindow", "M13"))
        self.BtnCreateMacros.setText(_translate("MainWindow", "Create/Edit Macros Set"))
        self.LblAvailable.setText(_translate("MainWindow", "COMs Available:"))
        self.LblStatusInfo.setText(_translate("MainWindow", "Not Connected"))
        self.LblTransmit.setText(_translate("MainWindow", "Transmit:"))
        self.LblStatus.setText(_translate("MainWindow", "Status:"))
        self.BtnSend.setText(_translate("MainWindow", "Send"))
        self.CBSTM.setText(_translate("MainWindow", "STM devices only"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Text Settings"))
        self.CBScroll.setText(_translate("MainWindow", "Scroll"))
        self.CBTime.setText(_translate("MainWindow", "Show Timestamp"))
        self.CBShowSent.setText(_translate("MainWindow", "Show sent "))
        self.BtnReScan.setText(_translate("MainWindow", "ReScan"))
        self.BtnConnect.setText(_translate("MainWindow", "Connect"))
        self.BtnClear.setText(_translate("MainWindow", "Clear"))
        self.BtnDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Counter"))
        self.LblCounter.setText(_translate("MainWindow", "Counter:"))
        self.BtnCounter.setText(_translate("MainWindow", "Clear Counter"))
        self.LblCounterData.setText(_translate("MainWindow", "0"))
        self.CBClear.setText(_translate("MainWindow", "Clear after sending"))
        self.groupBox_6.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton_2.setText(_translate("MainWindow", "Send File"))
        self.pushButton.setText(_translate("MainWindow", "Select File"))
        self.label.setText(_translate("MainWindow", "File Selected: None"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))

